### ISSUE TITLE
Release 0.6.2 - Expose Indicator Instances

### ISSUE THREAD

**Issue by dandxy89** [amv-dev/yata#32]
Hey @amv-dev 

Would it be possible to publish a new release such that the changes from [8212f0a](https://github.com/amv-dev/yata/commit/8212f0a7bdf1fbb50774c60e1c571ec54a8d50d1) are available?

Workaround:

```toml
# Technical Analysis
[dependencies.yata]
git = "https://github.com/amv-dev/yata.git"
rev = "5820314"
features = ["serde"]
optional = true
```
